//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.17.3.0 (NJsonSchema v9.10.46.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace Matchmore.SDK
{
    public class BaseClient
    {
        private string _apiKey { get; }

        public BaseClient(string apiKey)
        {
            this._apiKey = apiKey;
        }

        protected Task<HttpRequestMessage> CreateHttpRequestMessageAsync(CancellationToken cancellationToken)
        {
            var request = new HttpRequestMessage();
            request.Headers.Add("api-key", _apiKey);

            return Task.Run(() => request);
        }
    }
}